*** Variables ***
${login_button}     //android.widget.Button[@resource-id="com.doonung.activity.staging:id/mb_onboarding_login_button"]
${login_input_username}     //android.widget.EditText[@resource-id="com.doonung.activity.staging:id/mb_login_username_edit_text"]
${login_input_password}     //android.widget.EditText[@resource-id="com.doonung.activity.staging:id/mb_login_password_edit_text"]
${login_button_inside}     //android.widget.Button[@resource-id="com.doonung.activity.staging:id/mb_login_button"] 
${choose_profile_manage}    //android.widget.TextView[@text="Choose profile"]
${login_incorrect}     //android.widget.TextView[@resource-id="com.doonung.activity.staging:id/mb_login_wronging_text_view"]
# ${before_buy_package}        
# ${buy_basic}        
# ${buy_package}        
# ${prompypay}        
# ${proceed_to_payment}        
# ${pay_prompypay}        