*** Variables ***
# ${livetv_page}    //android.widget.FrameLayout[@content-desc="Live TV"]
# ${mono29}    //androidx.compose.ui.platform.ComposeView/android.view.View/android.view.View/android.view.View[1]/android.view.View[9]/android.view.View
# ${monomax1}    //androidx.compose.ui.platform.ComposeView/android.view.View/android.view.View/android.view.View[1]/android.view.View[6]/android.view.View

# internal
${livetv_page}    //android.widget.FrameLayout[@content-desc="Live TV"]
${mono29free}    //androidx.compose.ui.platform.ComposeView/android.view.View/android.view.View/android.view.View[1]/android.view.View[9]/android.view.View
${mono29}    //androidx.compose.ui.platform.ComposeView/android.view.View/android.view.View/android.view.View[1]/android.view.View[12]/android.view.View
${monomax1}    //androidx.compose.ui.platform.ComposeView/android.view.View/android.view.View/android.view.View[1]/android.view.View[7]/android.view.View