*** Variables ***
# ${sport_home}    //android.widget.FrameLayout[@content-desc="Sport"]
# ${match_live}    //androidx.compose.ui.platform.ComposeView/android.view.View/android.view.View/android.view.View[1]/android.view.View[2]/android.view.View[1]
# ${popup_login}    //android.widget.Button[@resource-id="com.doonung.activity.staging:id/button_cta1"]
# ${popup_noti}    //android.widget.Button[@resource-id="android:id/button1"]
# ${allow_button}    //android.widget.Button[@resource-id="com.android.permissioncontroller:id/permission_allow_button"]
# ${select_package}    //android.widget.TextView[@resource-id="com.doonung.activity.staging:id/mb_buy_package_title_text_view"]
# ${upcoming_hours}    //android.widget.TextView[@text="Hours"]
# ${upcoming_day}    //android.widget.TextView[@text="day"]
# ${upcoming_days}    //android.widget.TextView[@text="days"]
# ${player_live}    //android.widget.TextView[@text="LIVE"]
# ${seemore}    //android.widget.Button
# ${enter_seemore}    //androidx.compose.ui.platform.ComposeView/android.view.View/android.view.View/android.view.View[3]/android.view.View
# ${concurrent}    //android.widget.TextView[@resource-id="com.doonung.activity.staging:id/tv_error_title"]
# ${close_concurrent}    //android.widget.Button[@resource-id="com.doonung.activity.staging:id/button_cta1"]


# internal
${sport_home}    //android.widget.FrameLayout[@content-desc="กีฬา"]
${match_live}    //androidx.compose.ui.platform.ComposeView/android.view.View/android.view.View/android.view.View[1]/android.view.View[5]/android.view.View[1]
${popup_noti}    //android.widget.Button[@resource-id="android:id/button1"]
${allow_button}    //android.widget.Button[@resource-id="com.android.permissioncontroller:id/permission_allow_button"]
${upcoming_hours}    //android.widget.TextView[@text="Hours"]
${upcoming_day}    //android.widget.TextView[@text="day"]
${upcoming_days}    //android.widget.TextView[@text="days"]
${player_live}    //android.widget.TextView[@text="LIVE"]
${seemore}    //android.widget.Button
${enter_seemore}    //androidx.compose.ui.platform.ComposeView/android.view.View/android.view.View/android.view.View[1]/android.view.View[4]/android.widget.Button
${concurrent}    //android.widget.TextView[@resource-id="com.doonung.activity:id/tv_error_title"]